config/routes.rb
Rails.application.routes.draw do
  resources :services
 # devise_for :users
  resources :users
  resources :countries

  get '/destroy_flag/:id', to: 'countries#destroy_flag', as: 'destroy_flag'
  patch '/update_roles/:id', to: 'users#update_roles', as: 'update_roles'

  #root :to => "countries#index"

  #pages high_voltage
  # scope "/:locale", locale: /en|fr/ do
  #   get "/pages/:id" => 'high_voltage/pages#show', :as => :page, :format => false
  # end

  get "/home" => 'pages#home'
  get "/about" => 'pages#about'
  get "/conditions" => 'pages#conditions'
  get "/dashboard" => 'pages#dashboard'
  get "/user_profil" => 'pages#user_profil'
  get "/user_edit_profil" => 'pages#user_edit_profil'
  get "/license_agreement" => 'pages#license_agreement'
  get "/autocomplete" => 'users#autocomplete'


  root :to => 'pages#home'
  #devise

  devise_for :users , path: "auth", path_names: {
                                                  sign_in: 'login',
                                                  sign_out: 'logout',
                                                  password: 'secret',
                                                  confirmation: 'verification',
                                                  unlock: 'unblock',
                                                  registration: 'register',
                                                  sign_up: 'sign_up'
                                                }, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get     "/register",      to:   "registrations#new",          as: 'sign_up'
    get     "/login",         to:   "devise/sessions#new",        as: 'sign_in'
    get     "/logout",        to:   "devise/sessions#destroy",    as: 'sign_out'
  end

  get     '/sign_up' => redirect('/register')
  get     '/auth/register' => redirect('/register')
  get     '/sign_in' => redirect('/login')
  get     '/sign_out' => redirect('/logout')


  # get '*unmatched_route', :to => 'application#render_not_found'
  get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Columns
  include GlobalID::Identification

  #Elastic Search Model
  searchkick
  #searchkick autocomplete: ['term'], text_start: ['term'], suggest: ["term"]


  #role
  rolify

  #adding role behaviour
  #resourcify

  belongs_to :country #, :class_name => 'Country'
#  after_commit :reindex_country


  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :agree_terms, type: Mongoid::Boolean
  field :city, type: String
  field :zip_code, type: String
  field :phone, type: String
  field :adresse, type: String
  field :civility, type: String

  field :admin, type: Mongoid::Boolean

  index({ city: 1  })


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :async,
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  field :confirmation_token,   type: String
  field :confirmed_at,         type: Time
  field :confirmation_sent_at, type: Time
  field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  validates :first_name, :last_name, presence: :true, :length => {:minimum => 3, :maximum => 30}
  validates :city, :zip_code, presence: :true, :on => :create, :length => {:minimum => 3, :maximum => 30}
  validates :email, presence: true

  validates :country, presence: { message: ": Vous devez choisir un pays"}

  VALID_CIVILITIES = %w(Mme Mrs. Mr Mr.)
  validates_inclusion_of :civility, :in => VALID_CIVILITIES, :message => ": Vous devez choisir une civilité valide", :on => :create


  # validates :agree_terms, acceptance: true
  validates :agree_terms, :presence => true, :on => :create

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX  }, :uniqueness => { case_sensitive: false  }
  validates :password, length: { minimum: 6  }, :on => :create

  #callbacks
  before_save :down_upcase_attributes


  #pagination
  paginates_per 10

  #scopes
  scope :confirmed, ->{ not where(:confirmed_at => nil) }
  scope :unconfirmed, ->{ where(:confirmed_at => nil) }
  scope :country_sort, ->{ asc(:country_id)  }

  ROLES = [:admin, :supervisor, :simpleuser]

  def down_upcase_attributes
    self.email = email.downcase
    self.first_name = first_name.upcase
    self.last_name = last_name.capitalize
  end

  def pretty_name
    "#{self.civility} #{self.first_name} #{self.last_name}"
  end

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      column_names = fields.keys
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end

  def search_data
    as_json only: [:first_name, :last_name, :email, :city, :zip_code, :phone, :adresse, :civitlity, :country]
    # or equivalently
    {
      first_name: first_name,
      last_name: last_name,
      email: email,
      city: city,
      zip_code: zip_code,
      phone: phone,
      adresse: adresse,
      civility: civility,
      country: country
    }
  end

  def self.search_query(param, page)
      User.search "%#{param}%", suggest: true, misspellings: {distance: 2}, page: page, per_page: 10
  end

#  def reindex_country
#    country.reindex # or reindex_async
#  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  helper_method :sort_column, :sort_direction, :sort_column_type

  before_action :set_user, only: [:show, :edit, :update, :destroy, :update_roles, :correct_user]
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]

  load_and_authorize_resource

  #before_action :correct_user, only: [:edit, :update]
  #before_action :admin_user,     only: [:destroy, :index]

  # GET /users
  def index
    app_title('All users')
    @elasticsearch_service = Service.service('ELASTICSEARCH')
    if params[:query].present?
      begin
        @users = User.search_query(params[:query], params[:page])
      rescue => e
       @elasticsearch_service.down
        @users = User.order("#{sort_column} #{sort_direction}").page params[:page]
        flash.now[:error] = "Search engine's service is not available. This bug will be report to the administrator. Thanks!"
      end
    else
      @users = User.order("#{sort_column} #{sort_direction}").page params[:page]
    end
    @all_users = User.order("#{sort_column} #{sort_direction}")
    @all_users = [current_user] if !current_user.is_admin?
    respond_to do |format|
      format.html
      format.js
      #authorize! :show, @project
      @filename = "users-#{DateTime.now.strftime("%Y-%m-%d_%H-%M-%S")}"
      #format.csv { send_data @all_users.to_csv, :filename => "#{@filename}.csv", :disposition => 'inline', :type => "multipart/related" } #To dowloaded csv format directly
      format.csv do
        stream = @all_users.to_csv
        send_data(stream, :type=>"text/csv",:filename => "#{@filename}.csv")
      end

      #format.xls { send_data @all_users.to_csv(col_sep: "\t") } #To dowloaded xls format directly
      #format.xls { headers["Content-Disposition"] = "attachment; filename=\"#{@filename}.xls\"" } #To dowloaded xls format by pass on view
      format.xls do
        stream = render_to_string(:template=>"users/index" )
        send_data(stream, :type=>"text/xls",:filename => "#{@filename}.xls")
        #, notice:  t('controllers.actions.create', :ressource => t('mongoid.models.user.one', :default => "User"))
      end
    end
  end

  # GET /users/1
  def show
    app_title(@user.pretty_name)
  end

  # GET /users/new
  def new
    app_title('New user')
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    app_title('Edit user')
  end

  def sign_up
    @title = app_title('Sign up')
    @user = User.new
  end


  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.welcome_email(@user).deliver_later
      redirect_to admin_user? ? @user : user_profil_path, notice:  t('controllers.actions.create', :ressource => t('mongoid.models.user.one', :default => "User"))
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update_attributes(user_params)
      # UserMailer.welcome_email(@user).deliver_later(wait: 1.minute)
      redirect_to admin_user? ? @user : user_profil_path, notice:  t('controllers.actions.update', :ressource => t('mongoid.models.user.one', :default => "User"))
    else
      render :edit
    end
  end

  # PATCH/PUT /users/1
  def update_roles
    @roles.each { |role| role_adder(role, @user) }
    if @user.save
      redirect_to admin_user? ? @user : user_profil_path, notice:  t('controllers.actions.update_roles', :ressource => t('mongoid.models.user.one', :default => "User"))
    else
      render :show
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice:  t('controllers.actions.destroy', :ressource => t('mongoid.models.user.one', :default => "User"))
  end

  def autocomplete
    render json: User.search(params[:query], fields: [{first_name: :text_start}], limit: 10).map(&:first_name)
    #render json: User.search(params[:query], fields: [{first_name: :text_start}, {last_name: :text_start}, {email: :text_start}, {city: :text_start}, {zip_code: :text_start}], operator: "or", limit: 10).map(&:name)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @roles = User::ROLES
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :admin, :country_id, :password, :password_confirmation, :agree_terms, :city, :zip_code, :adresse, :phone, :civility)
    end

    def correct_user
      redirect_to(request.referrer)  unless current_user == @user
    end

    def sort_column
      User.fields.keys.include?(params[:sort]) ? params[:sort] : "country_id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end

    def sort_column_type
      %w[alpha numeric amount].include?(params[:type]) ?  params[:type] : "alpha"
    end

end

app/views/users/_form.html.slim
= simple_form_for @user, :html => { :class => "form-horizontal" } do |f|
  /! = f.error_notification
  = field_set_tag do
    legend "Information sur l'utilisateur"
    = render 'errors/errors_messages', object: f.object

    .row
      .form-group.col-xs-12.col-md-3
        = f.label :civility, "Civility"
        '
        = f.select(:civility, t('form.civility'), :include_blank => true)

      .form-group.col-md-1
      .form-group.col-xs-12.col-md-5
        strong Vous devez accepter les conditions générales d'utilisation
        br
        = f.input_field :agree_terms, as: :boolean
      .form-group.col-md-1
      .form-group.col-xs-12.col-md-4
        = f.label :country_id, "Pays"
        '
        = f.collection_select :country_id, Country.name_sort, :_id, :name
        - if @user.country
          .form-group.col-md-2
          = image_tag @user.country.flag.url(:thumb)

    .row
      .form-group.col-xs-12.col-md-5
        = f.input :first_name, label: "Nom", input_html: {class: 'form-control', placeholder: 'nom', maxlength: 50 }, error_html: { class: 'input_error' }
      .form-group.col-md-1
      .form-group.col-xs-12.col-md-5
        = f.input :last_name, label: "Prénom", input_html: {class: 'form-control', placeholder: 'prénom', maxlength: 50}, error_html: { class: 'input_error' }
    .row
      .form-group.col-xs-12.col-md-5
        = f.input :email, label: "E-mail", type: :email, input_html: {class: 'form-control', placeholder: '@', maxlength: 50 }, error_html: { class: 'input_error' }
      .form-group.col-md-1
      .form-group.col-xs-12.col-md-5
        = f.input :phone, label: "Telephone", type: :tel, input_html: {class: 'form-control', placeholder: '06 00 00 00 00', maxlength: 10 }, error_html: { class: 'input_error' }

    .row
      .form-group.col-xs-12.col-md-5
        = f.input :adresse, label: "Adresse", input_html: {class: 'form-control', placeholder: 'Adresse', maxlength: 70 }, error_html: { class: 'input_error' }
      .form-group.col-md-1
      .form-group.col-xs-12.col-md-2
        = f.input :city, label: "City", input_html: {class: 'form-control', placeholder: 'Ville', maxlength: 50 }, error_html: { class: 'input_error' }
      .form-group.col-md-1
      .form-group.col-xs-12.col-md-2
        = f.input :zip_code, label: "Code Postal", input_html: {class: 'form-control', placeholder: 'Code Postal', maxlength: 50 }, error_html: { class: 'input_error' }


    - unless @edit_profile
      .row
        .form-group.col-xs-12.col-md-5
          = f.input :password, autocomplete: "off"
        .form-group.col-md-1
        .form-group.col-xs-12.col-md-5
          = f.input :password_confirmation, label: 'Confirmation', autocomplete: "off"

  .form-actions.col-sm-offset-3
    = f.button :submit, :class => 'btn-primary'
    '

    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_user? ? users_path : user_profil_path, :class => 'btn btn-default'

app/views/users/_show_user.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize
  br

.row
  .form-group.col-xs-12.col-md-8.col-md-push
    .panel.panel-default
      .panel-heading
        h3.panel-title.text-center Les informations saisies
      br
      .panel-body
        .row
          .form-group.col-xs-12.col-md-5
            strong= model_class.human_attribute_name(:civility) + ':'
            '
            = @user.civility
        .row
          .form-group.col-xs-12.col-md-5
            strong= model_class.human_attribute_name(:first_name) + ':'
            '
            = @user.first_name
          .form-group.col-md-1
          .form-group.col-xs-12.col-md-5
            strong= model_class.human_attribute_name(:last_name) + ':'
            '
            = @user.last_name
        .row
          .form-group.col-xs-12.col-md-5
            strong= model_class.human_attribute_name(:email) + ':'
            '
            = @user.email
          .form-group.col-md-1
          .form-group.col-xs-12.col-md-2
            strong= model_class.human_attribute_name(:phone) + ':'
            '
            = @user.phone
          / .form-group.col-md-1
          / .form-group.col-xs-12.col-md-2

        .row
          .form-group.col-xs-12.col-md-5
            strong= "Country :"
            '
            = @user.country.name
            '
            /!= image_tag @user.country.flag.url(:thumb)
          .form-group.col-md-1

          .form-group.col-xs-12.col-md-5
            strong= model_class.human_attribute_name(:city) + ':'
            '
            = @user.city

        .row
          .form-group.col-xs-12.col-md-5
            strong= model_class.human_attribute_name(:adresse) + ':'
            '
            = @user.adresse
          .form-group.col-md-1
          .form-group.col-xs-12.col-md-5
            strong= model_class.human_attribute_name(:zip_code) + ':'
            '
            = @user.zip_code

      - if user_has_access_to_admin_panel?
        .panel-footer
          = "#{t("form.user_role_title")} : "
          = user_roles_tag(@user)

  .form-group.col-xs-12.col-md-4.col-md-pull
    .thumbnail
      = image_tag @user.country.flag.url(:thumb)
      .caption
        h3= "#{@user.country.name} (+#{@user.country.indicatif})"
        span
          | Nombre d'utilisateurs enregistrés :
          = bootstrap_badge_for(@user.country.users_count)
  .form-group.col-xs-12.col-md-2
  - if  admin_user?

    .form-group.col-xs-12.col-md-4.col-md-pull
      = simple_form_for @user, url: update_roles_path(@user), :html => { :method => :patch, :class => "form-horizontal" } do |f|
        fieldset
          legend=t("form.user_role_title")
          - @roles.each do |role|
            = hidden_field_tag(role, 0)
            = check_box_tag(role, 1, @user.has_role?(role))
            '
            = f.label(role)
            '
            br

        .form-actions.col-sm-offset-3
          = f.button :submit, 'Mettre à jour les roles', :class => 'btn-primary', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } , :class => 'btn btn-primary btn-xs'
            '
  br
  br
  .row
  br
  br

app/views/users/_sidebar.html.slim
- model_class = User
ul.nav.nav-list
  li.nav-header =t '.title', :default => model_class.model_name.human.pluralize.titleize
  li= link_to t('.new', :default => t("helpers.links.new_ressource", model: "#{t '.title', :default => model_class.model_name.human.titleize}")), new_user_path
  li= link_to "Link 2", "/path2"
  li= link_to "Link 3", "/path3"

app/views/users/_users_list.html.slim
- @users.each do |user|
  tr
    td= link_to user.pretty_name, user_path(user)
    td.hidden-xs= user.email
    td= user.city
    td.text-center= bootstrap_label_for(user.confirmed?)
    td.hidden-xs
      = link_to t('.show', :default => t("helpers.links.show")), user_path(user), :class => 'btn btn-default btn-xs'
      '
      /!.send_confirmation_instructions
.row
  .center-row.col-lg-9
    = paginate @users, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm pager pagination-centered"

app/views/users/_users_list0.html.slim
- model_class = User
table class="table table-striped table-condensed table-hover"
  thead
    tr
      /! th= model_class.human_attribute_name(:country_id)
      th= link_to_sortable :first_name, model_class.human_attribute_name(:name)
      th.hidden-xs= model_class.human_attribute_name(:email)
      th= link_to_sortable :country_id, model_class.human_attribute_name(:country_id)
      /!
        - if admin_user?
          th= link_to_sortable :admin, model_class.human_attribute_name(:admin)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @users.each do |user|
      tr
        td= link_to user.pretty_name, user_path(user)
        td.hidden-xs= user.email
        td= image_tag user.country.flag.url(:thumb)
          /! td= check_box_tag user.admin
          /!
            - if admin_user?
              td= bootstrap_label_for(user.admin, 'warning')
        td
          - if current_user?(user)
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          '
          - if admin_user?
            = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
          - else
            = link_to t('.show', :default => t("helpers.links.show")), user_path(user), :class => 'btn btn-default btn-xs'
.row
  .center-row.col-lg-9
    = paginate @users, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm pager pagination-centered"
br
br

app/views/users/edit.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
  - if admin_user?
    p.center-row.col-lg-2
      | Download :
      '
      | -
      /!link_to "CSV", users_path(format: "csv")
      '
      ||
      '
      = link_to "Excel", users_path(format: "xls")

= render "layouts/search_bar"
br
br
#users_list0
  = render 'users/users_list0' 
p
  - if admin_user?
    = link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/index.js.erb
$("#users_list0").html("<%= escape_javascript(render partial: 'users/users_list0', locals: { :@users => @users } ) %>");
$("#search_errors_explanation").html("<%= escape_javascript(bootstrap_flash) %>");

app/views/users/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="<%= @filename %>">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Pays</Data></Cell>
        <Cell><Data ss:Type="String">Ville</Data></Cell>
        <Cell><Data ss:Type="String">Code Postal</Data></Cell>
        <Cell><Data ss:Type="String">Adresse</Data></Cell>
        <Cell><Data ss:Type="String">Nom</Data></Cell>
        <Cell><Data ss:Type="String">Prenom</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Telephone</Data></Cell>
        <Cell><Data ss:Type="String">Date Identification</Data></Cell>
        <Cell><Data ss:Type="String">Confirmation du compte</Data></Cell>

      </Row>
    <% @all_users.each do |user| %>
      <Row>
        <Cell><Data ss:Type="String"><%= user.country_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.city %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= user.zip_code %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.adresse %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.first_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.last_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.phone %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.created_at %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.confirmed? %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/users/new.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.slim
= render :partial => 'show_user'

.row
  .form-actions.col-sm-offset-3
    = link_to t('.back', :default => t("helpers.links.back")), admin_user? ? users_path : root_path, :class => 'btn btn-default'
    '
    - if current_user?(@user)
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
      '
    - if admin_user?
      = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'