config/routes.rb
Rails.application.routes.draw do
  resources :services
 # devise_for :users
  resources :users
  resources :countries

  get '/destroy_flag/:id', to: 'countries#destroy_flag', as: 'destroy_flag'
  patch '/update_roles/:id', to: 'users#update_roles', as: 'update_roles'

  #root :to => "countries#index"

  #pages high_voltage
  # scope "/:locale", locale: /en|fr/ do
  #   get "/pages/:id" => 'high_voltage/pages#show', :as => :page, :format => false
  # end

  get "/home" => 'pages#home'
  get "/about" => 'pages#about'
  get "/conditions" => 'pages#conditions'
  get "/dashboard" => 'pages#dashboard'
  get "/user_profil" => 'pages#user_profil'
  get "/user_edit_profil" => 'pages#user_edit_profil'
  get "/license_agreement" => 'pages#license_agreement'
  get "/autocomplete" => 'users#autocomplete'


  root :to => 'pages#home'
  #devise

  devise_for :users , path: "auth", path_names: {
                                                  sign_in: 'login',
                                                  sign_out: 'logout',
                                                  password: 'secret',
                                                  confirmation: 'verification',
                                                  unlock: 'unblock',
                                                  registration: 'register',
                                                  sign_up: 'sign_up'
                                                }, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get     "/register",      to:   "registrations#new",          as: 'sign_up'
    get     "/login",         to:   "devise/sessions#new",        as: 'sign_in'
    get     "/logout",        to:   "devise/sessions#destroy",    as: 'sign_out'
  end

  get     '/sign_up' => redirect('/register')
  get     '/auth/register' => redirect('/register')
  get     '/sign_in' => redirect('/login')
  get     '/sign_out' => redirect('/logout')


  # get '*unmatched_route', :to => 'application#render_not_found'
  get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }
end

app/views/pages/_mentions_legales.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <style>
  body {
      position: relative;
  }
  ul.nav-pills {
      position: fixed;
  }
  div.col-sm-9 div {
      height: 250px;
      font-size: 28px;
  }
  #section1 {color: #fff; background-color: #1E88E5;}
  #section2 {color: #fff; background-color: #673ab7;}
  #section3 {color: #fff; background-color: #ff9800;}
  #section41 {color: #fff; background-color: #00bcd4;}
  #section42 {color: #fff; background-color: #009688;}

  @media screen and (max-width: 810px) {
    #section1, #section2, #section3, #section41, #section42  {
        margin-left: 150px;
    }
  }
  </style>
</head>
<body data-spy="scroll" data-target="#myScrollspy" data-offset="20">

<div class="container">
  <div class="row">
    <nav class="col-sm-3" id="myScrollspy">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="#section1">Section 1</a></li>
        <li><a href="#section2">Section 2</a></li>
        <li><a href="#section3">Section 3</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Section 4 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#section41">Section 4-1</a></li>
            <li><a href="#section42">Section 4-2</a></li>
          </ul>
        </li>
      </ul>
    </nav>
    <div class="col-sm-9">
      <div id="section1">
        <h1>Section 1</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
      </div>
      <div id="section2">
        <h1>Section 2</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
      </div>
      <div id="section3">
        <h1>Section 3</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
      </div>
      <div id="section41">
        <h1>Section 4-1</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
      </div>
      <div id="section42">
        <h1>Section 4-2</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/pages/_mentions_legales1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <style>
  .test {
      position: relative;
      height: 400px;
      overflow: auto;
  }
  #section1 {color: #fff; background-color: #1E88E5;}
  #section2 {color: #fff; background-color: #673ab7;}
  #section3 {color: #fff; background-color: #ff9800;}
  #section41 {color: #fff; background-color: #00bcd4;}
  #section42 {color: #fff; background-color: #009688;}
  </style>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><a href="#section1">Section 1</a></li>
          <li><a href="#section2">Section 2</a></li>
          <li><a href="#section3">Section 3</a></li>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Section 4 <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#section41">Section 4-1</a></li>
              <li><a href="#section42">Section 4-2</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

<div data-spy="scroll" data-target=".navbar" data-offset="12" class="test">
  <div id="section1">
    <div class="container-fluid">
      <h1>Section 1</h1>
      <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
      <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
    </div>
  </div>
  <div id="section2">
    <div class="container-fluid">
      <h1>Section 2</h1>
      <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
      <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
    </div>
  </div>
  <div id="section3">
    <div class="container-fluid">
      <h1>Section 3</h1>
      <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
      <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
    </div>
  </div>
  <div id="section41">
    <div class="container-fluid">
      <h1>Section 4 Submenu 1</h1>
      <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
      <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
    </div>
  </div>
  <div id="section42">
    <div class="container-fluid">
      <h1>Section 4 Submenu 2</h1>
      <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
      <p>Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!</p>
    </div>
  </div>
</div>

</body>
</html>

app/views/pages/_mentions_legales2.html.slim
doctype html
html
  head
    title Bootstrap Example
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" /
    script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"
    script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"
    css:
      .test {
          | position: relative;
          | top: 50px;
          | height: 200px;
          | overflow: auto;
          | font-size: 28px;
      | }
      #section1  color: #fff; background-color: #1E88E5;
      #section2  color: #fff; background-color: #673ab7;
      #section3  color: #fff; background-color: #ff9800;
      #section41  color: #fff; background-color: #00bcd4;
      #section42  color: #fff; background-color: #009688;
  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container-fluid
        .navbar-header
          button.navbar-toggle data-target="#myNavbar" data-toggle="collapse" type="button"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"  Mentions légales
        div
          #myNavbar.collapse.navbar-collapse
            ul.nav.navbar-nav
              li
                a href="#section1"  Section 1
              li
                a href="#section2"  Section 2
              li
                a href="#section3"  Section 3
              li.dropdown
                a.dropdown-toggle data-toggle="dropdown" href="#"
                  | Section 4
                  span.caret
                ul.dropdown-menu
                  li
                    a href="#section41"  Section 4-1
                  li
                    a href="#section42"  Section 4-2
    .test data-offset="12" data-spy="scroll" data-target=".navbar"
      #section1
        .container-fluid
          h1 Editeur du site
          p
            cfeb-france.org
            par coordination diplomatique CFEB-France
            S/C Ambassade du Niger en France,
            154 rue de Longchamp 75116 Paris.
            France
            Tél. : + 33 (0)0 00 00 00 00
            Fax : + 33 (0)0 00 00 00 00
            http://www.cfeb-france.org
            coordination@cfeb-france.org
            N° déclaration CNIL : 18 77 495


          p Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!
          p Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!
      #section2
        .container-fluid
          h1 Section 2
          p Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!
          p Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!
      #section3
        .container-fluid
          h1 Section 3
          p Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!
          p Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!
      #section41
        .container-fluid
          h1 Section 4 Submenu 1
          p Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!
          p Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!
      #section42
        .container-fluid
          h1 Section 4 Submenu 2
          p Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!
          p Try to scroll this section and look at the navigation bar while scrolling! Try to scroll this section and look at the navigation bar while scrolling!

app/views/pages/_user_form.html.slim
= simple_form_for @user, :html => { :class => "form-horizontal" } do |f|
  = f.error_notification
  = field_set_tag do
    legend Information sur l'utilisateur
    .row
      .form-group.col-xs-12.col-md-5
        = f.input :first_name, label: "Nom", input_html: {class: 'form-control', placeholder: 'nom', maxlength: 50 }, error_html: { class: 'input_error' }
      .form-group.col-md-1
      .form-group.col-xs-12.col-md-5
        = f.input :last_name, label: "Prénom", input_html: {class: 'form-control', placeholder: 'prénom', maxlength: 50}, error_html: { class: 'input_error' }
    .row
      .form-group.col-xs-12.col-md-5
        = f.input :email, label: "E-mail", type: :email, input_html: {class: 'form-control', placeholder: '@', maxlength: 50 }, error_html: { class: 'input_error' }
      .form-group.col-md-1
      .form-group.col-xs-12.col-md-5
        strong Est un admin?
        br
        = f.input_field :admin, as: :boolean

    .row
      .form-group.col-xs-12.col-md-5
        = f.label :country_id
        = f.collection_select :country_id, Country.name_sort, :_id, :name
      .form-group.col-md-1

    - unless @edit_profile
      .row
        .form-group.col-xs-12.col-md-5
          = f.input :password
        .form-group.col-md-1
        .form-group.col-xs-12.col-md-5
          = f.input :password_confirmation, label: 'Confirmation'

  .form-actions.col-sm-offset-3
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default'

app/views/pages/about.html.slim
.page-header
  h1 Qui sommes nous ?

.col-lg-10.col-lg-offset-1
  .row.center-block
    /!.col-sm-9.col-md-7-offset-2
    .thumbnail
      .caption
        h3 CFEB-FRANCE
        p
          = Settings.application_about_us_main_text
          '
          a href="#{Settings.application_about_us_link_url}" target="_blank" role="link"  Nous contacter.

app/views/pages/dashboard.html.slim
.page-header
  h1 Dashboard
.row
  - @countries.each do |country|
    .col-sm-6.col-md-4
      .thumbnail
        = image_tag country.flag.url(:thumb)
        .caption
          h3= link_to "#{country.name} (+#{country.indicatif})", country_path(country)
          span
            | Nombre d'utilisateurs enregistrés :
            = bootstrap_badge_for(country.users_count)
.row
  .center-row.col-lg-9
    = paginate @countries, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm pager pagination-centered"
br
br

app/views/pages/home.html.slim
.page-header
  h1= t('form.page_home_title')

.row
  .col-sm-12.col-md-4.col-md-offset-4
    .flat_menu
      .thumbnail
        .caption
          - if signed_in?
            = image_tag("logo-cfeb-france.png", height: '140', width: '140', class: "img-circle")
          - else
            = link_to t('form.sign_in'), sign_in_path, class: "btn btn-primary btn-xl"
            p
            = link_to t('form.sign_up'), sign_up_path, class: "btn btn-success btn-xl"
        .center-row
          button.btn.btn-success.btn-link data-target="#guideModal" data-toggle="modal" type="button"  Guide
          | |
          = mail_to  "coordination@cfeb-france.org", "Nous écrire", class: "btn btn-success btn-link"
          | |
          = link_to  "Mentions légales", conditions_path, class: "btn btn-success btn-link"
      .center-row.text-center
        = render :partial => 'shareable/social_links'

.container
  /! Modal
  #guideModal.modal.fade role="dialog"
    .modal-dialog
      /! Modal content
      .modal-content
        .modal-header
          button.close data-dismiss="modal" type="button"  &times;
          h2.modal-title Guide de l'utilisateur
        .modal-body
          h3 Procédure d'identification
          p
            | La plateforme est mise à disposition pour permettre aux nigériens résidant en France, en Espagne au Portugal et au Royaume Uni de s'identifier. Et ceci, pour préciser, leurs coordonnées et positions géographiques afin d'en tenir compte dans le choix des points fixes de recensement.
            br
            b
              | Pour plus de détails, merci de consulter les démarches du
              '
              = link_to  "recensement.", "http://www.cfeb-france.org/index.php/demarches/", target: "_blank"
        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  Close

app/views/pages/user_edit_profil.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "users/form"

app/views/pages/user_profil.html.slim
= render :partial => 'users/show_user'
.row
  .form-actions.col-sm-offset-3
  = link_to t('.back', :default => t("helpers.links.back")), root_path, :class => 'btn btn-default'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), user_edit_profil_path, :class => 'btn btn-default'
  '
  - if admin_user?
    = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'