config/routes.rb
Rails.application.routes.draw do
  resources :services
 # devise_for :users
  resources :users
  resources :countries

  get '/destroy_flag/:id', to: 'countries#destroy_flag', as: 'destroy_flag'
  patch '/update_roles/:id', to: 'users#update_roles', as: 'update_roles'

  #root :to => "countries#index"

  #pages high_voltage
  # scope "/:locale", locale: /en|fr/ do
  #   get "/pages/:id" => 'high_voltage/pages#show', :as => :page, :format => false
  # end

  get "/home" => 'pages#home'
  get "/about" => 'pages#about'
  get "/conditions" => 'pages#conditions'
  get "/dashboard" => 'pages#dashboard'
  get "/user_profil" => 'pages#user_profil'
  get "/user_edit_profil" => 'pages#user_edit_profil'
  get "/license_agreement" => 'pages#license_agreement'
  get "/autocomplete" => 'users#autocomplete'


  root :to => 'pages#home'
  #devise

  devise_for :users , path: "auth", path_names: {
                                                  sign_in: 'login',
                                                  sign_out: 'logout',
                                                  password: 'secret',
                                                  confirmation: 'verification',
                                                  unlock: 'unblock',
                                                  registration: 'register',
                                                  sign_up: 'sign_up'
                                                }, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get     "/register",      to:   "registrations#new",          as: 'sign_up'
    get     "/login",         to:   "devise/sessions#new",        as: 'sign_in'
    get     "/logout",        to:   "devise/sessions#destroy",    as: 'sign_out'
  end

  get     '/sign_up' => redirect('/register')
  get     '/auth/register' => redirect('/register')
  get     '/sign_in' => redirect('/login')
  get     '/sign_out' => redirect('/logout')


  # get '*unmatched_route', :to => 'application#render_not_found'
  get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }
end

app/models/country.rb
class Country
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include Columns

  #adding role behaviour
  resourcify

  has_many :users, dependent: :restrict

  field :_id, type: String, default: ->{ name }
  field :name
  #field :name, type: String
  #field :flag, type: String
  field :indicatif, type: Integer
  field :enable, type: Mongoid::Boolean, default: false

  has_mongoid_attached_file :flag, :styles => {
                                                :thumb => '50x50',
                                                :small    => '100x100#',
                                                :medium   => '250x250',
                                                :large    => '500x500>'
                                              },
                                                :default_url => "missing/:style/missing-image.png",
                                                :default_style => :medium,
                                                :url => "/system/:class/:attachment/:id/:style/:basename.:extension",
                                                :path => ":rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension"

  index({ name: 1  })


  validates_attachment_content_type :flag, :content_type => /\Aimage\/.*\Z/
  validates :name,
            presence: true,
            uniqueness: { message: "Ce nom existe déjà"}
  validates_length_of :name, :in => 2..25
  validates :indicatif,
            presence: true,
            uniqueness: { message: "un autre pays possède dejà ce t'indicatif"},
            :inclusion => { in: 1..999, :message => "Merci de saisir une valeur entre 1 et 999" }


  #pagination
  paginates_per 10

  #scopes
  # asc(:name)
  scope :indicatif_sort, ->{ asc(:indicatif)  }
  scope :name_sort, ->{ where(:enable => true).asc(:name) }

  def change_flag
    flag = nil
    save
    file = File.open(Rails.root.join('app', 'assets', 'images', 'missing','medium' ,'missing-image.png'))
    flag = file
    file.close
    save
  end

  def users_count
    users.count
  end

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  include ApplicationHelper
  helper_method :sort_column, :sort_direction, :sort_column_type

  before_action :set_country, only: [:show, :edit, :update, :destroy, :destroy_flag]

  before_action :authenticate_user!
  #before_action :admin_user, only: [:index, :show, :edit, :update, :destroy, :destroy_flag]
  load_and_authorize_resource

  # GET /countries
  def index
    app_title('All Countries')
    @countries = Country.order("#{sort_column} #{sort_direction}").page params[:page]
    authorize! :read, @countries
  end

  # GET /countries/1
  def show
    app_title(@country.name)
    @users = @country.users.order("created_at asc").page params[:page]
    @all_users = @country.users.order("created_at asc")
    @all_users = [current_user] if !current_user.is_admin?
    respond_to do |format|
      format.html
      @filename = "#{@country.name}-#{DateTime.now.strftime("%Y-%m-%d_%H-%M-%S")}"
      #format.csv { send_data @all_users.to_csv, :filename => "#{@filename}.csv", :disposition => 'inline', :type => "multipart/related" } #To dowloaded csv format directly
      format.csv do
        stream = @all_users.to_csv
        send_data(stream, :type=>"text/csv",:filename => "#{@filename}.csv")
      end


      format.xls do
        stream = render_to_string(:template=>"users/index" )
        send_data(stream, :type=>"text/xls",:filename => "#{@filename}.xls")
      end
    end
  end

  # GET /countries/new
  def new
    app_title('New Country')
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
    app_title('Edit Country')
  end

  # POST /countries
  def create
    @country = Country.new(country_params)

    if @country.save
      redirect_to @country, notice:  t('controllers.actions.create', :ressource => t('mongoid.models.country.one', :default => "Country"))
    else
      render :new
    end
  end

  # PATCH/PUT /countries/1
  def update
    if @country.update_attributes(country_params)
      redirect_to @country, notice:  t('controllers.actions.update', :ressource => t('mongoid.models.country.one', :default => "Country"))
    else
      render :edit
    end
  end

  # DELETE /countries/1
  def destroy
    if @country.users.empty?
      @country.flag = nil
      @country.destroy
      redirect_to countries_url, notice: t('controllers.actions.destroy', :ressource => t('mongoid.models.country.one', :default => "Country"))
    else
      redirect_to request.referrer, alert: t('controllers.actions.destroy_restrict', :ressource => t('mongoid.models.country.one', :default => "Country"))
    end
  end

  # DELETE /countries/1
  def destroy_flag
    @country.change_flag
    redirect_to @country, notice: t('controllers.actions.destroy_flag')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def country_params
      params.require(:country).permit(:name, :flag, :indicatif, :enable)
    end

    def sort_column
      Country.fields.keys.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end

    def sort_column_type
      %w[alpha numeric amount].include?(params[:type]) ?  params[:type] : "alpha"
    end
end

app/views/countries/_form.html.slim
= simple_form_for @country, :html => { :class => "form-horizontal" } do |f|
  = f.error_notification
  = field_set_tag do
    legend Information sur le pays
    .row
      .form-group.col-xs-12.col-md-5
        = f.input :name, label: "Nom du Pays", input_html: {class: 'form-control', placeholder: 'Ex: France', maxlength: 50 }, error_html: { class: 'input_error' }
      .form-group.col-md-1
      .form-group.col-xs-12.col-md-2
        = f.input :indicatif, label: "L'indicatif", input_html: {class: 'form-control', placeholder: '+33', maxlength: 3}, error_html: { class: 'input_error' }
      .form-group.col-md-1
      .form-group.col-xs-12.col-md-3
        strong Est actif?
        br
        = f.input_field :enable, as: :boolean
    .form-group
      = f.file_field :flag, as: :file, label: "Merci d'ahouter un drapeau"
      p.help-block Cliquez pour ajouter un drapeau
  .form-actions.col-sm-offset-3
    = f.button :submit, :class => 'btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), countries_path, :class => 'btn btn-default'

app/views/countries/_sidebar.html.slim
- model_class = Country
ul.nav.nav-list
  li.nav-header =t '.title', :default => model_class.model_name.human.pluralize.titleize
  li= link_to t('.new', :default => t("helpers.links.new_ressource", model: "#{t '.title', :default => model_class.model_name.human.titleize}")), new_country_path
  li= link_to "Link 2", "/path2"
  li= link_to "Link 3", "/path3"

app/views/countries/edit.html.slim
- model_class = Country
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/countries/index.html.slim
- model_class = Country
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped table-condensed table-hover"
  thead
    tr
      th= link_to_sortable :name, model_class.human_attribute_name(:name)
      th.hidden-xs= link_to_sortable :indicatif, model_class.human_attribute_name(:indicatif), :numeric
      th= link_to_sortable :enable, model_class.human_attribute_name(:enable), :default
      th= model_class.human_attribute_name(:users)
      th= model_class.human_attribute_name(:flag)
      - if admin_user?
        th.hidden-xs=t '.actions', :default => t("helpers.actions")
  tbody
    - @countries.each do |country|
      tr
        td= link_to country.name, country_path(country)
        td.hidden-xs= "(+#{country.indicatif})"
        td= bootstrap_label_for(country.enable)
        td= bootstrap_badge_for(country.users_count)
        td= image_tag country.flag.url(:thumb)
        - if admin_user?
          td.hidden-xs
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_country_path(country), :class => 'btn btn-default btn-xs'
            '
            = link_to t('.destroy', :default => t("helpers.links.destroy")), country_path(country), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

.row
  .center-row.col-lg-9
    = paginate @countries, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm pager pagination-centered"
br
br
- if current_user.has_role? :admin
  = link_to t('.new', :default => t("helpers.links.new")), new_country_path, :class => 'btn btn-primary'

app/views/countries/new.html.slim
- model_class = Country
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/countries/show.html.slim
- model_class = Country
div class="page-header"
  .row
    .col-xs-12.col-md-5
      .img-thumbnail
        = image_tag @country.flag.url(:medium)
      p
        - if @country.flag.exists? && admin_user?
          = link_to t('.destroy', :default => t("helpers.links.destroy_flag")), destroy_flag_path(@country), :method => "get", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } , :class => 'btn btn-link btn-xs'
    .col-xs-12.col-md-5
      h1= @country.name
      br
      .text-center
        = link_to t('.back', :default => t("helpers.links.back")), countries_path, :class => 'btn btn-default btn-xs'
        '
        - if admin_user?
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_country_path(@country), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), country_path(@country), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-xs'


br
.panel.panel-default
  .panel-heading
    h3.panel-title
    .row
      .form-group.col-xs-12.col-md-3
        strong= "#{model_class.human_attribute_name(:name)} : #{@country.name}"
      .form-group.col-xs-12.col-md-3.hidden-xs
        strong= "#{model_class.human_attribute_name(:indicatif)} : (+ #{@country.indicatif})"
      .form-group.col-xs-12.col-md-3
        strong= "#{model_class.human_attribute_name(:enable)} : "
        '
        = bootstrap_label_for(@country.enable)
      .form-group.col-xs-12.col-md-3
        strong Nombre d'utilisateurs :
        '
        = bootstrap_badge_for(@country.users_count)


  .panel-body
    .row
      - unless @users.empty?
        - inner_model_class = User
        div class="text-center"
          h1=t '.title', :default => inner_model_class.model_name.human.pluralize.titleize
          - if admin_user?
            p.center-row.col-lg-2
              | Download :
              '
              | -
              /!link_to "CSV", users_path(format: "csv")
              '
              ||
              '
              = link_to "Excel", country_path(format: "xls")
          hr
        table class="table table-striped table-condensed table-hover"
          thead
            tr
              th= inner_model_class.human_attribute_name(:name)
              th.hidden-xs= inner_model_class.human_attribute_name(:email)
              th= inner_model_class.human_attribute_name(:city)
              th.text-center=t '.account.confirmation', :default => "Confirmation du compte"
              th.hidden-xs=t '.actions', :default => t("helpers.actions")
          tbody
            = render :partial => 'users/users_list'