config/routes.rb
Rails.application.routes.draw do
  resources :services
 # devise_for :users
  resources :users
  resources :countries

  get '/destroy_flag/:id', to: 'countries#destroy_flag', as: 'destroy_flag'
  patch '/update_roles/:id', to: 'users#update_roles', as: 'update_roles'

  #root :to => "countries#index"

  #pages high_voltage
  # scope "/:locale", locale: /en|fr/ do
  #   get "/pages/:id" => 'high_voltage/pages#show', :as => :page, :format => false
  # end

  get "/home" => 'pages#home'
  get "/about" => 'pages#about'
  get "/conditions" => 'pages#conditions'
  get "/dashboard" => 'pages#dashboard'
  get "/user_profil" => 'pages#user_profil'
  get "/user_edit_profil" => 'pages#user_edit_profil'
  get "/license_agreement" => 'pages#license_agreement'
  get "/autocomplete" => 'users#autocomplete'


  root :to => 'pages#home'
  #devise

  devise_for :users , path: "auth", path_names: {
                                                  sign_in: 'login',
                                                  sign_out: 'logout',
                                                  password: 'secret',
                                                  confirmation: 'verification',
                                                  unlock: 'unblock',
                                                  registration: 'register',
                                                  sign_up: 'sign_up'
                                                }, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get     "/register",      to:   "registrations#new",          as: 'sign_up'
    get     "/login",         to:   "devise/sessions#new",        as: 'sign_in'
    get     "/logout",        to:   "devise/sessions#destroy",    as: 'sign_out'
  end

  get     '/sign_up' => redirect('/register')
  get     '/auth/register' => redirect('/register')
  get     '/sign_in' => redirect('/login')
  get     '/sign_out' => redirect('/logout')


  # get '*unmatched_route', :to => 'application#render_not_found'
  get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }
end

app/views/layouts/_footer.html.slim
  .container
    .text-center
      p.text-muted.credit
        ' Copyright &copy;
        = link_to Settings.application_full_name, root_path
        '  #{DateTime.now.year}
        /! designed by link_to Settings.application_designer, Settings.application_designer_url, target: 'blanck'

app/views/layouts/_head.html.slim
head
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  title= content_for?(:title) ? yield(:title) : @title
  = csrf_meta_tags

  /! Le HTML5 shim, for IE6-8 support of HTML elements
  /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
  = stylesheet_link_tag "application", :media => "all"

  = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
  = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
  = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
  = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
  = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
  = javascript_include_tag "application"

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/" CFEB-France - Admin
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to t('mongoid.models.user.other', :default => "Users"), users_path
          span.sr-only (current)
        li= link_to t('mongoid.models.country.other', :default => "Countries"), countries_path
      / form.navbar-form.navbar-left role="search"
      /   .form-group
      /     input.form-control placeholder="Search" type="text" /
      /   button.btn.btn-default type="submit"  Submit
      ul.nav.navbar-nav.navbar-right
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            | Compte
            span.caret
          ul.dropdown-menu
            li
              = link_to current_user do
                i.fa.fa-user.fa-fw
                '
                | Profil
            li
              = link_to edit_user_path(current_user)   do
                i.fa.fa-cog
                '
                | Paramètres
            li.divider
            li
              = link_to destroy_user_session_path, title: "Se déconnecter" do
                i.fa.fa-sign-out
                '
                | Se déconnecter
    /! /.navbar-collapse
  /! /.container-fluid

app/views/layouts/_login_items.html.slim
- if user_signed_in?
  = link_to destroy_user_session_path, class: "btn btn-default", title: "Se déconnecter" do
    i.fa.fa-sign-out

  - if user_has_access_to_admin_panel?
    = link_to dashboard_path, class: "btn btn-default", title: "Accéder à l'interface d'administration" do
      i.fa.fa-cog
- else
  = link_to new_user_session_path, class: "btn btn-default", title: "Se connecter" do
    i.fa.fa-sign-in

app/views/layouts/_page_menu.html.slim
.btn-group
  = link_to user_profil_path, class: "btn btn-default", title: "Accéder à votre compte!" do
    i.fa.fa-user.fa-fw
  = render :partial => 'layouts/login_items'
  button.btn.btn-default.dropdown-toggle data-toggle="dropdown" type="button" title="Menu"
    | Menu
    span.caret
    span.sr-only Toggle Dropdown
  ul.dropdown-menu role="menu"
    li
      = link_to root_path do
        i.fa.fa-home
        '
        | Accueil
    li
      = link_to about_path do
        i.fa.fa-question-circle
        '
        | Qui sommes nous?
    li.divider
    li
      = link_to conditions_path, class: "link" do
        i.fa.fa-book
        '
        | Conditions d'uitlisation

app/views/layouts/_plateforme_footer.html.slim
p style=("text-align: center; vertical-align: middle; padding-top: 20px; height: 40px; background-image: linear-gradient(to bottom, #ffffff, #f2f2f2); border: 1px solid #d4d4d4")
  ' Copyright &copy;
  = link_to Settings.application_full_name, 'http://plateforme.cfeb-france.org'
  '  #{DateTime.now.year}

app/views/layouts/_plateforme_title.html.slim
h1 style=("color: #CF732A")
  span #
  span style=("color: #2B5391")
    | CFEB-France -
  span Identification

hr style=("display: block; height: 1px; border: 0px; border-top: 2px solid #CF732A; margin: 1em 0; padding: 0;")

app/views/layouts/_search_bar.html.slim
- if @elasticsearch_service.try(:status)
  = form_tag users_path, method: :get, remote: true do
    .row.center-row
      .col-lg-8.col-lg-offset-2
        #search_errors_explanation
      .col-lg-8.col-lg-offset-2
        .input-group
          = text_field_tag :query, params[:query], class: "form-control typeahead", placeholder: 'Enter search term...', id: "query", autocomplete: "off", name: "query"
          span.input-group-btn
            button.btn.btn-default type="submit" class="btn search-query"
              i class="fa fa-search"
  /
    javascript:
      $("#query").typeahead(
      {
        hint: true,
        highlight: true,
        minLength: 1
      },
      { 
        name: "first_name",
        remote: "/autocomplete?query=%QUERY"
      });

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    = render :partial => 'layouts/head'

  body
    /!-- Wrap all page content here
    #wrap
      = render :partial => 'layouts/header'

      /!begin page content
      .container.dashboard
        .row
          .col-lg-12
            = bootstrap_flash
            = yield
          /! .col-lg-3
          /!   .well.sidebar-nav
          /!     h3 Sidebar
          /!     /= render :partial => 'sidebar'


  /!begin page footer
  footer
    = render :partial => 'layouts/footer'

app/views/layouts/login.html.slim
.container
  #loginbox.mainbox.col-md-6.col-md-offset-3.col-sm-8.col-sm-offset-2 style="margin-top:50px;" 
    .panel.panel-info
      .panel-heading
        .panel-title Sign In
        div style=("float:right; font-size: 80%; position: relative; top:-10px") 
          a href="#"  Forgot password?
      .panel-body style="padding-top:30px" 
        #login-alert.alert.alert-danger.col-sm-12 style="display:none" 
        form#loginform.form-horizontal role="form" 
          .input-group style=("margin-bottom: 25px") 
            span.input-group-addon
              i.glyphicon.glyphicon-user
            input#login-username.form-control name="username" placeholder=("username or email") type="text" value="" /
          .input-group style=("margin-bottom: 25px") 
            span.input-group-addon
              i.glyphicon.glyphicon-lock
            input#login-password.form-control name="password" placeholder="password" type="password" /
          .input-group
            .checkbox
              label
                input#login-remember name="remember" type="checkbox" value="1" /
                | Remember me
          .form-group style="margin-top:10px" 
            /! Button
            .col-sm-12.controls
              a#btn-login.btn.btn-success href="#"  Login
              a#btn-fblogin.btn.btn-primary href="#"  Login with Facebook
          .form-group
            .col-md-12.control
              div style=("border-top: 1px solid#888; padding-top:15px; font-size:85%") 
                | Don't have an account!
                a href="#" onclick=("$('#loginbox').hide(); $('#signupbox').show()") 
                  | Sign Up Here
  #signupbox.mainbox.col-md-6.col-md-offset-3.col-sm-8.col-sm-offset-2 style=("display:none; margin-top:50px") 
    .panel.panel-info
      .panel-heading
        .panel-title Sign Up
        div style=("float:right; font-size: 85%; position: relative; top:-10px") 
          a#signinlink href="#" onclick=("$('#signupbox').hide(); $('#loginbox').show()")  Sign In
      .panel-body
        form#signupform.form-horizontal role="form" 
          #signupalert.alert.alert-danger style="display:none" 
            p Error:
            span
          .form-group
            label.col-md-3.control-label for="email"  Email
            .col-md-9
              input.form-control name="email" placeholder=("Email Address") type="text" /
          .form-group
            label.col-md-3.control-label for="firstname"  First Name
            .col-md-9
              input.form-control name="firstname" placeholder=("First Name") type="text" /
          .form-group
            label.col-md-3.control-label for="lastname"  Last Name
            .col-md-9
              input.form-control name="lastname" placeholder=("Last Name") type="text" /
          .form-group
            label.col-md-3.control-label for="password"  Password
            .col-md-9
              input.form-control name="passwd" placeholder="Password" type="password" /
          .form-group
            label.col-md-3.control-label for="icode"  Invitation Code
            .col-md-9
              input.form-control name="icode" placeholder="" type="text" /
          .form-group
            /! Button
            .col-md-offset-3.col-md-9
              button#btn-signup.btn.btn-info type="button" 
                i.icon-hand-right
                | \&nbsp Sign Up
              span style="margin-left:8px;"  or
          .form-group style=("border-top: 1px solid #999; padding-top:20px") 
            .col-md-offset-3.col-md-9
              button#btn-fbsignup.btn.btn-primary type="button" 
                i.icon-facebook
                |   Sign Up with Facebook

app/views/layouts/page_layout.html.slim
doctype html
html lang="en"
  head
    = render :partial => 'layouts/head'

  body
    /!-- Wrap all page content here
    #wrap
      /!= render :partial => 'layouts/header'
      /!begin page content
      .container
        .row
          .col-lg-12
            .public
              .row.text-center
                .col-lg-9.text-left style=("padding: 0 5px")
                  = link_to root_path do
                    h1
                      span #
                      span.t1 CFEB-France - 
                      span Identification
                .col-lg-3.pull-right style=("padding-top:20px")
                - if signed_in?
                  = render :partial => 'layouts/page_menu'
              hr
            = bootstrap_flash
            = yield

  /!begin page footer
  footer
    = render :partial => 'layouts/footer'